template:
  name: "MyKerasModel_template"
  description: "Keras MNIST Model testing template"
  model_class: "MyKerasModel"
  requirements:
    - tensorflow==2.9.0
    - opencv-python-headless==4.5.5.64
    - protobuf<4.*,>=3.20.1
instance:
  name: "my_mnist_model"
  version: 1
  description: "Instance for the Keras MNIST model"
  weights_path: resources/my_model
deploy:
  orchestrator: "AWS_EKS"
  skip_build: false
  properties: {}
  enable_cuda: false
  redeploy: true
  build_all_layers: true
  download_base: false
  update_weights: true
  overwrite: true
  push: true